<link href="style.css" rel="stylesheet" type="text/css" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="google-site-verification" content="QRRJBqey9zvCC-1xEGP7PCwHymnp2cwWPq3BFFh0WGE" />
<meta name="keywords" content="Aromathérapeute nancy, phytothérapeute nancy, medecine douce, bien etre, sante bien etre, naturel, conseil , produit naturel, soin naturel, aromathérapie , phytothérapie, aromathérapie nancy, phytothérapie nancy,medecine douce nancy, laetitia Di Labio - Courcelle" />
<meta name="description" content="Propose une médecine douce par l'aromathérapie et phytothérapie" />
<meta name="author" content="Laetitia Di Labio - Courcelle" />
<meta name="copyright" content="@ tous droits réservés" />
<meta http-equiv="Content-Language" content="fr" />
<meta name="robots" content="index,follow" />

<link href="/img/favicon.ico" rel="icon" type="image/x-icon" />
