<div id="footer">
Identifiant SIREN : 527 592 232 <br />
<a href="http://sante-bien-etre-au-naturel.com/">Page de garde</a> | 
<a href="mailto:webmaster@sante-bien-etre-au-naturel.com">contacter le webmaster</a> | 
&copy; 2010 Yann Courcelle <br />
Sur la base du travail de <a href="http://www.mitchinson.net"> www.mitchinson.net</a> sur le template CSS greenpiece<br />
Le CSS de ce site est sous licence <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 License</a>
</div>
